version: '3.8'

services:
  flask-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_USER=savalverde
      - MONGO_PASSWORD=qgMCctgVSrUQQxgC
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    dns:
      - 8.8.8.8
    depends_on:
      - redis
    networks:
      - flask_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
